[package]
name = "jems-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
jems-core = { path = "../jems-core" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rocksdb = { version = "0.21", default-features = false, features = ["lz4"] }
thiserror = "1.0"
