[timing]
slot_secs=4
epoch_slots=21600
[committee]
size=64
[difficulty]
ema_alpha=0.25
blocks_per_epoch_target=21600
[emission]
total_supply=100000000
reward_split={leader=60,committee=20,honeypot=15,ecosys=5}
[tickets]
w_max=1000000
lambda_decay=0.80
cap_per_epoch=10000
rate_per_slot_max=5
weights={like=5,checkin=50,relay=25,post=40,visit=200}
[honeypot]
bounty_min=10000
bounty_max=100000
expiry_k_epochs=7
trigger_catalog=["6th_like_today","12th_checkin_today","nth_visit_landmark"]
[fees]
min_tx_fee_microjem=1000
committee_rebate_bp=1000
[rpc]
max_req_bytes=1000000
max_array_len=5000
rate_limit_qps=50
